### ISSUE TITLE
[CKEditor 4/5] Math formulas with arrows not rendering correctly

### ISSUE THREAD

**Issue by Mgsy** [wiris/html-integrations#10]
Original issue - https://github.com/ckeditor/ckeditor5/issues/5993.

## Steps to reproduce
1.  In empty paragraph click 'insert math formula'
2.  Click on 'arrow tab'
3.  Choose one of the arrows with a single number placeholder (above or below)
4.  Type some numbers before the arrow, after the arrow and in the placeholder

## Expected result
Numbers should render right above or below the arrow, arrow should change its width.

## Actual result
With longer formulas numbers are rendering in wrong place.

## Other details

![mathtype_arrow_formula_error](https://user-images.githubusercontent.com/34380544/71005186-7e7ce200-20e3-11ea-877a-f657e07c4276.gif)

**Comment by carlawiris** [comment]
We have been studying the problem and we have realized that it is not a mathtype problem but a problem with the way a formula with arrows is treated:

 

The problem is that you are writing in the arrow container and not out of it, you can detect it because the bottom caret marks the arrow and not the whole equation (which would be the expected).

To see the correct behavior you have to move the cursor one more position to the right when inserting an arrow.

We attached a video showing the difference between the behavior you have reported and the correct behavior in this type of formulas:


![z2](https://user-images.githubusercontent.com/60604864/96426337-642cfc80-11fd-11eb-9422-207e58529364.gif)
