### ISSUE TITLE
`onOK` handler in Mathtype

### ISSUE THREAD

**Issue by dcanetma** [wiris/html-integrations#116]
## Are you reporting a feature request or a bug?

> Originally reported at https://github.com/ckeditor/ckeditor4/issues/4268

It's a feature request

<img alt="Screen Shot 2020-09-08 at 5 20 09 PM" width="716" src="https://user-images.githubusercontent.com/51118408/92489897-f9010b00-f1f8-11ea-8016-071d7e23e82f.png">

I would like to know when `OK` is clicked in Mathtype Panel. Is there `onOK` handler for this purpose?

## Other details

* Browser: Version 85.0.4183.83 (Official Build) (64-bit)

* OS: OSX

* Integration version:

* CKEditor version: latest (`npm install ckeditor4-react`)

* Installed CKEditor plugins: https://www.npmjs.com/package/@wiris/mathtype-ckeditor4

**Comment by carla-at-wiris** [comment]
Hi @dcanet-at-wiris,

I believe we don't have a specific listener for this but the `onAfterFormulaInsertion` current listener of ours, will do the trick, since it is called every time a formula is inserted, or modified, which is also every time the '**ok**' button is clicked.

More information about how this listener works on [this thread](https://github.com/wiris/html-integrations/issues/356#issuecomment-897419676).
