### ISSUE TITLE
[CKEditor 5] CKEditor error: Cannot read property 'match' of undefined when clicking 'Insert Code Block' after the formula

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#13]
Tested on new version, branch `ckeditor5-demo`

#### Steps to reproduce:
   - add a formula
   - click 'Insert Code Block' in the toolbar
  
Result:
  ```js
  Uncaught TypeError: Cannot read property 'match' of undefined
    at getLeadingWhiteSpaces (utils.js:88)
    at getLastOutdentableSequenceRange (outdentcodeblockcommand.js:136)
    at outdentcodeblockcommand.js:107
    at Array.some (<anonymous>)
    at OutdentCodeBlockCommand._checkEnabled (outdentcodeblockcommand.js:106)
    at OutdentCodeBlockCommand.refresh (outdentcodeblockcommand.js:40)
    at Document.<anonymous> (command.js:111)
    at Document.fire (emittermixin.js:209)
    at Document._handleChangeBlock (document.js:318)
    at Model._runPendingChanges (model.js:787)
   ```

**Comment by carlawiris** [comment]
Hi, thanks for reporting this behavior.

I've been able to reproduce the issue following the steps you informed. But I think the behavior here is the expected since we treat the formulas as images. it happens the same when using some image not added from the MathType plugin.

I mean, the behavior with the 'Insert code block' plugin is the same as the one you expose in this issue with all images.

We were wondering, as the error occurs also with images that are not formulas, if the solution of this issue was on your side. What do you think?
![z2-online-video-cuttercom](https://user-images.githubusercontent.com/60604864/98090863-ee739280-1e84-11eb-8c59-b97307bf1574.gif)

**Comment by FilipTokarski** [comment]
Hi, thanks for the insights! I checked it once again and I still reproduce the original error but cannot reproduce the error only with images. When I upload images and insert `codeBlock`, everything works fine:  

![0_mathtype3](https://user-images.githubusercontent.com/34380544/98099393-cb021500-1e8f-11eb-868d-d47a10f01aab.gif)
  
When inserting the formula and then `codeBlock` I get:  
  
![0_mathtype2](https://user-images.githubusercontent.com/34380544/98099507-f38a0f00-1e8f-11eb-96c5-3ee916ad8ee9.gif)
  
I'm using custom editor built from source with CKEditor plugins in latest version ( 23.1.0 ) + MathType 7.24.1. I get the same results in Chrome, Firefox and Safari ( I'm checking this on mac ).  
You can check if it works for you on our [Code Blocks demo](https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#demo) - there's no image upload icon here, but you can paste image inside the editor.
Maybe I'm missing some steps to reproduce this error with just the images? 🤔

**Comment by carlawiris** [comment]
Thank you for the feedback, we will be working on it.

**Comment by carlawiris** [comment]
We have released a new version that solves this bug, it is the 7.26.0
