### ISSUE TITLE
[CKEditor 5] Safari - Error after undoing remove MathType equation with comment

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#23]
## 📝 Provide detailed reproduction steps (if any)

Original issue: https://github.com/ckeditor/ckeditor5/issues/6481

1. Open editor with MathType and Comments
2. Add a MathType equation
3. Select the equation and add a comment
4. Remove the equation
5. Undo

### ✔️ Expected result

Removal is undone, equation appears again together with comment

### ❌ Actual result

Editor crashes:
```js
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'i[Hc("0x4")]')
	Uc (ckeditor.js:6:26826)
	isValidTarget (ckeditor.js:5:89529)
	(anonymous function) (ckeditor.js:5:79722)
	attachTo (ckeditor.js:5:86490)
	(anonymous function) (ckeditor.js:6:32100)
	promiseReactionJob
	parseFromString
	_toDom (ckeditor.js:5:196200)
	toView (ckeditor.js:5:196108)
	(anonymous function) (ckeditor.js:6:24486)
	view (ckeditor.js:6:24555)
	(anonymous function) (ckeditor.js:5:291919)
	fire (ckeditor.js:5:34727)
	_testAndFire (ckeditor.js:5:291210)
	convertInsert (ckeditor.js:5:288370)
	convertChanges (ckeditor.js:5:287688)
	(anonymous function) (ckeditor.js:5:301202)
	change (ckeditor.js:5:281283)
	(anonymous function) (ckeditor.js:5:301159)
	fire (ckeditor.js:5:34727)
	_handleChangeBlock (ckeditor.js:5:347976)
	_runPendingChanges (ckeditor.js:5:365243)
	enqueueChange (ckeditor.js:5:362252)
	execute (ckeditor.js:5:420128)
	(anonymous function) (ckeditor.js:5:30691)
	fire (ckeditor.js:5:34727)
	execute (ckeditor.js:5:303502)
	execute (ckeditor.js:5:367251)
	(anonymous function) (ckeditor.js:5:422748)
	fire (ckeditor.js:5:34727)
	(anonymous function) (ckeditor.js:5:25240)
	n (ckeditor.js:5:158417)
	fire (ckeditor.js:5:34727)
	i (ckeditor.js:5:165410)
```

![24_comment1](https://user-images.githubusercontent.com/34380544/77400074-ee69cb00-6daa-11ea-868a-21f5b341df84.gif)

## 📃 Other details

* Browser: Safari

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by carla-at-wiris** [comment]
Hello @FilipTokarski,

Sorry for the late response, but we've been trying to reproduce the issue and faced some problems with the comments plugin.

First, we received a license key to try out the plugin, and then we tried a simple integration of the `comments` plugin on a basic CKEditor5, without our MathType plugin. Here's what we tried and the problems we encountered:
* When following the exact same instructions on[ this page](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-integration.html).
 
![image](https://user-images.githubusercontent.com/60604864/145553641-47e5a73b-4149-4809-be63-e3e66d02dd96.png)
![image](https://user-images.githubusercontent.com/60604864/145553654-a9d6a47f-b415-4f26-a211-e33f82d9c5db.png)


* When building an Angular application, creating a custom build to integrate and enable the comments plugin:
* 
![image](https://user-images.githubusercontent.com/60604864/145553706-37875f24-8b0e-42bd-89e9-09e6a3809556.png)


* When including the comments plugin to an application built following this guide. We've created the custom build with the comments plugin and included the ckeditor.js file on the code, as the ClassicEditor
![image](https://user-images.githubusercontent.com/60604864/145553753-ceb22805-12c3-42cf-8485-21cf6986043e.png)
    ```js
    import * as ClassicEditor from '../build/ckeditor';
    
    window.editor = null;
    
    // Create the CKeditor5.
    ClassicEditor
      .create(document.querySelector('#editor'), {
        licenseKey: 'our-license-key',
        toolbar: ['bold', 'italic', 'alignment:left', 'alignment:center', 'alignment:right', 'comment'],
      })
      .then((editor) => {
        window.editor = editor;
        editor.editing.view.focus();
      });
    ```

We believe that maybe we're integrating in the wrong way the plugin, but, since we followed your instructions and also got an error message, I wonder if maybe this is on your side? If not, could you provide us a workaround so we can integrate the plugin on a basic CKEditor5 app?

**Comment by carla-at-wiris** [comment]
Hello @FilipTokarski,

This issue is no longer reproducible in the latest versions of both plugins: mathtype-ckeditor5 and CKEditor5 comments ones.
