### ISSUE TITLE
Cannot read property 'getSelection' of null, when clicked to close or cancel button

### ISSUE THREAD

**Issue by doox911** [wiris/html-integrations#330]
## Description

Initialization passes without errors. When clicked dialog will open. And I can't close or cancel.

Vue Component:
```
<template>
  <div>
    <div id="toolbarLocation" />
    <div
      id="example"
      contenteditable="true"
    >
      Try me!
    </div>
  </div>
</template>

<script lang="ts">
  import { Component, mixins, Prop } from 'nuxt-property-decorator';

  @Component
  export default class WirisGeneric extends mixins() {
    private wiris_generic;

    protected mounted(): void {
      const genericIntegrationProperties = {};

      genericIntegrationProperties.target = document.getElementById('example');
      genericIntegrationProperties.toolbar = document.getElementById('toolbarLocation');

      this.wiris_generic = new WirisPlugin.GenericIntegration(genericIntegrationProperties);

      this.wiris_generic.init();
      this.wiris_generic.listeners.fire('onTargetReady', {});
    }
  }
</script>
```

nuxt.config.js:
```
  plugins: [
    {
      src: './node_modules/@wiris/mathtype-generic/wirisplugin-generic.js',
      mode: 'client',
    },
  ],
```

## Environment

*What is the relevant software and their versions?*

package.json:
```
  "dependencies": {
    "@apollo/client": "^3.3.20",
    "@wiris/mathtype-generic": "^7.27.0",
    "apollo-link-http": "^1.5.17",
    "apollo-upload-client": "^16.0.0",
    "cookie-universal-nuxt": "^2.1.5",
    "core-js": "^3.9.1",
    "graphql": "^15.5.1",
    "lodash": "^4.17.21",
    "mime-types": "^2.1.31",
    "nuxt": "^2.15.3",
    "nuxt-property-decorator": "^2.9.1",
    "react": "^17.0.2",
    "vue-nl2br": "^0.1.2",
    "vuedraggable": "^2.24.3"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^1.21.6",
    "@graphql-codegen/typescript": "^1.22.4",
    "@mdi/font": "^5.9.55",
    "@nuxt/types": "^2.15.3",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/eslint-config-typescript": "^6.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/stylelint-module": "^4.0.0",
    "@nuxtjs/vuetify": "^1.11.3",
    "@types/apollo-upload-client": "^14.1.0",
    "@types/lodash": "^4.14.170",
    "@types/mime-types": "^2.1.0",
    "@types/react": "^17.0.13",
    "@typescript-eslint/eslint-plugin": "^4.27.0",
    "@typescript-eslint/parser": "^4.27.0",
    "@vue/test-utils": "^1.1.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.29.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-import-resolver-nuxt": "^1.0.1",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.11.1",
    "eslint-plugin-vuetify": "^1.0.1",
    "jest": "^26.6.3",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "stylelint": "^13.12.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^21.0.0",
    "ts-jest": "^26.5.4",
    "typescript": "^4.3.4",
    "vue-jest": "^3.0.4",
    "vue-router": "^3.5.2",
    "vuetify": "^2.5.5"
  }
```
![bag](https://user-images.githubusercontent.com/35161922/127450649-216188ee-3d43-4b92-b6ca-8b56d8fb286f.png)

## Expected result

The dialog should close

## Actual result

Dialogue does not close.

Error:
> wirisplugin-generic.js?588c:formatted:2549 Uncaught TypeError: Cannot read property 'getSelection' of null
    at Function.value (wirisplugin-generic.js?588c:formatted:2549)
    at e.value (wirisplugin-generic.js?588c:formatted:2933)

**Comment by carla-at-wiris** [comment]
Hi @doox911, thank you for contacting us.

We did an investigation and the problem you are experiencing it is not an issue. Here is what you can do to get rid of it and have the cancel and close buttons working again:

**Comment by carla-at-wiris** [comment]
Hi @doox911, thank you for contacting us.

The problem is that, with the code you are using to integrate the Wiris Generic plugin, you are not defining an important element (also necessary for other MathType functionalities) called currentInstance.

Here is what you can do to integrate the plugin with the currentInstance object, so you'll have the cancel and close buttons working again:

- Use the window wiris function to initialize the Generic integration: 
  ```
  window.wrs_int_init(taget, toolbar)
  ```
  instead of this part of your code below: 
  ```
  this.wiris_generic = new WirisPlugin.GenericIntegration(genericIntegrationProperties);

  this.wiris_generic.init();
  this.wiris_generic.listeners.fire('onTargetReady', {});
  ```
  Our function contains the same code you are using, with some other definitions necessary to build the currentInstance object.

- Import the `wrsInitEditor` function from '`/node_modules/@wiris/mathtype-generic/wirisplugin-generic.js`', and use it to initialize the editor: `wrsInitEditor(target, toolbar)`, same behaviour as the previous point, you have to use our function instead of your last 3 lines of code.
- Manually, create a definition of the current instance: following your code, will be something like this: 
  `WirisPlugin.currentInstance = this.wiris_generic;`. In this case, you can add this line to your code. My recomentadtion would be after the fire of 'onTargetReady' listener.
- In the **worst of the cases**, you can downgrade your mathtype-generic plugin to the version 7.26.1.

The first 3 options, are all great to solve your problem, none of them is better than the other, so choose the one you find more interesting.

If you have more issues, please feel free to contact us again.

**Comment by doox911** [comment]
WirisPlugin.currentInstance = this.wiris_generic; - works.

Thank you very match!
