### ISSUE TITLE
[CKEditor 5] The Math/Chem feature does not work in iOS (Safari)

### ISSUE THREAD

**Issue by oleq** [wiris/html-integrations#38]
1.  Go to https://ckeditor.com/docs/ckeditor5/latest/features/math-equations.html#demo
2.  Press the "Insert math equation" button.

**Expected**:

The UI shows up providing a minimal UX for the user to create a new equation.

**Actual**:

Instead of the math UI, there's an overlay that cover the entire web page and there's no way to close it and go back to the editing. It breaks the editing experience in the editor.

![](https://user-images.githubusercontent.com/1099479/82676425-ae0db880-9c46-11ea-832a-8deb0bb5f9f4.jpeg)

**Comment by dcanetma** [comment]
Hi, Oleq

I'm glad to inform you that the issue should be solved in our last release of both `mathtype-ckeditor5` and `mathtype-html-integration-devkit packages`, published yesterday.

Unfortunately, the MathType demo in the CKEditor website you have shared is outdated, so you will not be able to validate it there.

> _It uses 7.14.0 version of the MathType SDK while the current version would be 7.24.1. o higher._
> It would be a good idea to update the [mathtype-ckeditor5 package](https://github.com/wiris/html-integrations/tree/stable/packages/mathtype-ckeditor5), when possible.


So, in order to validate the issue is solved, I'd suggest to try one of CKEditor demos at this very same repository.

You'll be able to check by yourself that the MathType modal window appears right on iOs devices.

These are some instructions to test it.

1. Clone this repository.
2. Checkout the 'master' branch, that contains the demos last versions.
3. Try any of the CKEditor demos * and validate it works fine on an iOs device

These would be the terminal commands:

```sh
# 1. Clone this repository.
$ git clone https://github.com/wiris/html-integrations.git
$ cd html-integrations
# 2. Checkout the 'master' branch, that contains the demos last versions.
$ git checkout master
# 3. Use the angular+ckeditor5 demo, for example, to test the MathType plugin.
$ cd demos/angular/ckeditor
$ npm install
$ npm start
```
Or, if you prefer you can try the online demo at wiris.com:

- http://www.wiris.com/plugins/demo/ckeditor4/php/

Let us know if the issue persists, please, or if you have any other issue.

Many thanks.


> _*: the 'html5/ckeditor5' demo is currently not compiling because a known issue with babeljs. You can try 'html5/ckeditor4', angular's or react's, though. Since the behaviour you've informed has todo do with the MathType SDK and not the the CKEditor plugin itself, regardless the version (CK4 or CK5)._
