### ISSUE TITLE
WirisPlugin.currentInstance is null when accessing it in `onInstanceReady` event of CKEditor4

### ISSUE THREAD

**Issue by henok-outlier** [wiris/html-integrations#420]
I would like to get the inputted mathtype when `Insert` button is clicked. And I've added the listener in `onInstanceReady` event of CKEditor, as described in this ticket https://github.com/wiris/html-integrations/issues/383#issuecomment-914200415. But `currentInstance` is null, and I'm getting `Cannot read properties of null (reading 'core')`

How to listen when `WirisPlugin` object is ready in CKEditor?

```
    window.WirisPlugin.currentInstance.core.listeners.add({
      eventName: "onAfterFormulaInsertion",
      callback: (params) => {
        console.log({ params });
      }
    });
```

Please check the sandbox as reference, https://codesandbox.io/s/ecstatic-cherry-pmjtk?file=/src/App.js.

**Comment by carla-at-wiris** [comment]
Hi @henok-outlier,

`WirisPlugin` takes a while to load and usually, it gets loaded at the same time as the editor. For what i see, the CKEditor4 with react loads faster than the `WirisPlugin` object, that's why you don't have it accessible on the `onInstanceReady` event.

I would suggest to try to wait until the object is ready instead of using the CKEditor event.

Good luck with your project.

Kind regards,
Integrations team.

**Comment by henok-outlier** [comment]
```
  listenMathtypeChange = () => {
    // WirisPlugin object is not ready yet in `onInstanceReady`
    // event of CKEditor, so we should check every second if
    // it's exposed in window object and has a valid `currentInstance` field.

    this.timeoutRef.current = setTimeout(() => {
      const instance = window.WirisPlugin?.currentInstance

      if (!instance) return this.listenMathtypeChange()

      instance.core.listeners.add(getFormulaInsertionEvent())

      clearTimeout(this.timeoutRef.current)
    }, [1000])
  }
```

yes, able to solve it using recursion. Thank you!
