### ISSUE TITLE
Long division with exponent in the upper part not rendering in CKEditor

### ISSUE THREAD

**Issue by henok-outlier** [wiris/html-integrations#440]
## Description

The CKEditor is not rendering inputs in the long division format. Putting anything with an exponent in the top portion of the block (see screenshot) causes nothing to show up when I press "Insert."

![image (2)](https://user-images.githubusercontent.com/72997506/136509428-2e319ec6-2585-4e6a-8835-e1bf69106ebc.png)

## Environment

"@wiris/mathtype-ckeditor4": "^7.27.1"
"@wiris/mathtype-ckeditor4": "^7.24.1",

- Editor (CKEditor)
- Framework ( React.)
- Browser (Chrome.)
- Operating System (macOS)

## Steps to reproduce

1. Open official CKEditor Mathtype demo page https://ckeditor.com/mathtype/demo/#ckeditor4
2. Open Mahtype
3. Enter the above long division formula appearing the screenshot

## Expected result

The long division formula should be inserted in the CKEditor

## Actual result

Formula is not displayed in the CKEditor and error is showing in the console

## Other details

When I wrap the top portion part with parenthesis, the formula is properly rendered.

**Comment by carla-at-wiris** [comment]
Hello @henok-outlier,

Thank you for reaching us. We've been having some trouble reproducing your issue. So we have some questions for you:
1. Have you tried to reproduce it in the web page you're indicating on the steps to reproduce section?
2. A video prof showing the steps you followed and the error that appears will help a lot.
3. Your code snippet or a demo of yours we can use to test the bug will be helpful.

**Comment by carla-at-wiris** [comment]
Thank you @henok-outlier, this helps! 

We'll add it to our backlog and start working on it as soon as we can.

Keep you updated!

**Comment by carla-at-wiris** [comment]
Hello @henok-outlier,

This issue has been sent to the responsible team of the solution inside our organization. We'll let you know once the solution is available.

**Comment by carla-at-wiris** [comment]
Hello @henok-outlier, we have some feedback from the responsible team on this matter.

First of all, thank your for the details provided.
This issue falls on the `MathType` editor services end, in this case in the rendering service. This is not a specific issue for the integration on a particular HTML editor.

Unfortunately, after further investigation, our Product/Engineering team would need to discard fixing this issue for the moment. Long divisions are intended for elementary mathematic contexts where using superscripts is not the common use case.

In order to have more details, since this issue has an open ticket on our Technical Support end, please provide us with more details of the exact use case of type of question you are trying to implement.
