### ISSUE TITLE
CORS policy -  configurationjs

### ISSUE THREAD

**Issue by atanas-filipov** [wiris/html-integrations#444]
## Description

CORS error

## Environment

- CKEditor
- * Browser: any
- *Operating System Windows 10

## Steps to reproduce

*I can provide access to the CMS if needed.

## Expected result

*Load without errors like the rest of the websites, including the ones, on the same hosting account

## Actual result

*See screenshot
![screenshot](https://user-images.githubusercontent.com/49340209/136793216-da2cb0e2-b581-4514-9ecf-f563501a5f27.JPG)

**Comment by Sumon-TWeb** [comment]
Hi @carla-at-wiris, Any update on this issue. we are still facing this issue while trying to insert the formula in the editor. 
We are using [@wiris/mathtype-ckeditor5 npm package
](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5) with CKEDITOR 5. 
Please suggest how to fix this issue is there any workaround?
Please check the attached error screenshot
![image](https://user-images.githubusercontent.com/61141437/142147373-46c1a322-5c6c-424e-a2c8-4c75021c684c.png)

**Comment by carla-at-wiris** [comment]
Hello @atanas-filipov, after further investigation we can confirm that your issue is in fact a license issue.
Please contact our sales team through sales@wiris.com or buy a license online.

**Comment by tjsudarsan-ts** [comment]
Hey, I too facing a similar issue currently. We have a paid licence, how to integrate that? There's no documentation on how to add the licence to the Wiris plugin in CkEditor. Thanks
