### ISSUE TITLE
"x" and "Cancel" buttons throwing "Uncaught TypeError: e is null" when clicked; not closing

### ISSUE THREAD

**Issue by rayvongregory** [wiris/html-integrations#499]

**Comment by dcanet-at-wiris** [comment]
Hi @rayvongregory 

Thanks for reporting.

We'd need more information so we can be able to reproduce the issue, though.

Could you provide more context on the issue you are experiencing?

Thanks!

**Comment by rayvongregory** [comment]
I used the steps on [npmjs.com](https://www.npmjs.com/package/@wiris/mathtype-generic) to install the latest version and to create three instances of the generic integration. When I open the MathType panel, all of the buttons work as expected except for the Close and Cancel buttons. When clicked, neither button closes the panel and they throw an error instead. 

In Firefox, the error is: 
" Uncaught TypeError: e is null
    value http://localhost:5500/mathtype/mathtype-generic/wirisplugin-generic.js:1
    value http://localhost:5500/mathtype/mathtype-generic/wirisplugin-generic.js:1
wirisplugin-generic.js:1:101687
    value http://localhost:5500/mathtype/mathtype-generic/wirisplugin-generic.js:1
    value http://localhost:5500/mathtype/mathtype-generic/wirisplugin-generic.js:1
    value self-hosted:1178  "

In Chrome: 
" Uncaught TypeError: Cannot read properties of null (reading 'getSelection')
    at Function.value (wirisplugin-generic.js:1)
    at e.value (wirisplugin-generic.js:1) "

The page I added the plugin to had other dependencies running on it so I thought maybe those other packages could have been interfering with MathType but I get the same errors even when it's the only thing on the page.

**Comment by carla-at-wiris** [comment]
Thanks for the new information @rayvongregory,

I've tried myself to reproduce the issue you mentioned on our development and production environments but everything works fine. In my honest opinion, It looks more like a possible error on the code you are using rather than a bug itself.

It would be very helpful if you could share the source code you are using on a code-sandbox platform like jsfiddle or similar. 

In order to get more help integrating MathType, I would suggest to please contact our Support Team at support@wiris.com.

**Comment by rayvongregory** [comment]
I copied the example code from npm and used unpkg to load the latest package. I am still getting the error.

[jsfiddle](https://jsfiddle.net/rayvongregory/oby9mjxk/8/)

**Comment by dcanet-at-wiris** [comment]
Thanks for your answer, @rayvongregory 

After checking the code on the jsFiddle you are providing, it seems that it's more an error on how are the plugin is used rather than a bug itself. 

Therefore, I suggest you to contact our Support Team at support@wiris.com with your question.

They will help you out.

Kind regards,

D.
