### ISSUE TITLE
CORS policy error requesting https://www.wiris.net/demo/plugins/app/configurationjs

### ISSUE THREAD

**Issue by Kanan02** [wiris/html-integrations#664]
## Description
Hello, in localhost my angular app works fine and does not show any errors about CORS however when I publish my front-end to myasp.net hosting it shows me CORS error in the part where mathtype component (ckeditor) should be executed.
Can you please help me understand where the error could be?
![Capture](https://user-images.githubusercontent.com/82045517/191788475-5fa90dfc-3ed4-47f9-b1b7-94ee7c8a7618.PNG)

**Comment by jguillen-at-wiris** [comment]
Hi Kanan, thanks for your request.

As per your screenshot, I understand you are using our demo download for ASP.NET, since it is trying to consume the configurationjs file from our wiris.net web server.

It is normal it works in your localhost, as you are consuming it from a client request. Although, when you run your app under your domain it turns into a domain to domain request, ending up in a CORS forbidden access error, due to our web server policies.

To set and host your own configuration file from your ASP.NET integration of our plugin, [following the steps in our documentation page.](https://store.wiris.com/en/products/downloads/mathtype/integrations?&_ga=2.256176011.1282443910.1665133913-337498423.1657027053#free_trial_individual)

Remember that you will have to edit your front-end editor configuration to consume that configuration file.
Also, please, make sure you are downloading the integration, not the demo.

Should we help you any other how, please, let us know. Thanks!!
