### ISSUE TITLE
SyntaxError: unknown file: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.

### ISSUE THREAD

**Issue by gokulramdev** [wiris/html-integrations#973]
## Description
SyntaxError: unknown file: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.

while I am using wiris generic react 

## Steps to reproduce
  Just follow the steps of the generic react

**Comment by carla-at-wiris** [comment]
Hello @gokulramdev, thank you for writing us!

We will take a look at your issue during this week. We will let you know about any news.

**Comment by TranLeMinh1234** [comment]
I have same issue. 
![image](https://github.com/wiris/html-integrations/assets/77385036/08589cf1-8481-4440-9a3f-beecc6e00250)

It's seem related xml structure in react+typescript project.

**Comment by carla-at-wiris** [comment]
Hello, thank you for writing us.

Since this seems to be a React JSX issue, we won't plan to work on it in the short term. If setting the flag `throwIfNamespace` to false works for you, we'd ask you to use it until we develop a way to make our SVG compatible with JSX. Any further issues, please feel free to contact us!
